name: Guard-dog vulnerability scanner

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r vulnscan/requirements.txt
      - name: Run scanner
        run: |
          python vulnscan/scan.py --min-severity LOW --output vuln-report.json || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: vuln-report
          path: vuln-report.json
